// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID       int64     `db:"id"`
	Owner    string    `db:"owner"`
	Balance  int64     `db:"balance"`
	Currency string    `db:"currency"`
	CreateAt time.Time `db:"create_at"`
}

type Entry struct {
	ID        int64     `db:"id"`
	AccountID int64     `db:"account_id"`
	Amount    int64     `db:"amount"`
	CreateAt  time.Time `db:"create_at"`
}

type Session struct {
	ID           uuid.UUID `db:"id"`
	Username     string    `db:"username"`
	RefreshToken string    `db:"refresh_token"`
	UserAgent    string    `db:"user_agent"`
	ClientIp     string    `db:"client_ip"`
	IsBlocked    bool      `db:"is_blocked"`
	ExpireDate   time.Time `db:"expire_date"`
	CreatedAt    time.Time `db:"created_at"`
}

type Transfer struct {
	ID        int64     `db:"id"`
	FromAccID int64     `db:"from_acc_id"`
	ToAccID   int64     `db:"to_acc_id"`
	Amount    int64     `db:"amount"`
	CreateAt  time.Time `db:"create_at"`
}

type User struct {
	Username          string    `db:"username"`
	HashedPassword    string    `db:"hashed_password"`
	FullName          string    `db:"full_name"`
	Email             string    `db:"email"`
	PasswordChangedAt time.Time `db:"password_changed_at"`
	CreatedAt         time.Time `db:"created_at"`
}
